### ISSUE TITLE
Could this just be done w/

### ISSUE THREAD

**Issue by walker** [picanteverde/init#2]
Could this just be done w /a custom Yeoman generator?

https://github.com/yeoman/yeoman/wiki/Generators

**Comment by picanteverde** [comment]
well actually you can't do this with Yeoman, not even in the actual state of the project. Yeoman is more for generating client apps templates and scafolds, here there is also a server app, not just serving files (has the server from yeoman) but also with an architecture prepared for large componetized apps, including (for now) a user manager and login strategy, but I intend to add more functionality in the near future, with also several drivers for object persistency as mongodb and postrgres

**Comment by walker** [comment]
Cool. I figured that might be part of it.
